-- create table fakemenu (id int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL, Cuisine varchar(20) NOT NULL, subCat varchar(14), menuItem varchar(25), price float, description varchar(120));
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Appetizers', 'Empanadas', 5, 'Tasty lil South American meat pastries');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Appetizers', 'Quesadilla', 7, 'Melted cheese and chicken fajita in a tortilla');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Appetizers', 'Nachos', 6, 'Chips with things on top of them');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Enchiladas', 'Suiza', 7, 'A swiss take on an enchilada');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Enchiladas', 'Al Pastor', 7, 'Pork enchiladas');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Enchiladas', 'Pulled Pork', 8, 'The greatest of all enchiladas');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Enchiladas', 'con Mole', 7, 'Enchiladas with a chocolatey mole sauce');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Fajitas', 'Chicken', 7, 'Sizzling plate of chicken fajita, served with tortillas, pico de gallo, rice, beans, and guacamole');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Fajitas', 'Beef', 10, 'Sizzling plate of beef fajita, served with tortillas, pico de gallo, rice, beans, and guacamole');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Fajitas', 'Mixed', 9, 'Sizzling plate of chicken and beef fajita, served with tortillas, pico de gallo, rice, beans, and guacamole');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Desert', 'Sweet Empanadas', 5, 'Tasty lil South American peach pastries');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Desert', 'Flan', 6, 'A squiggly cake');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Mexican', 'Desert', 'Tamarind Candies', 4, 'Those little spicey corn on a stick-s');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Appetizers', 'Chicken Sa-Te', 7, 'Flamegrilled chicken on a skewer, served with peanut sauce.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Appetizers', 'Beef Sa-Te', 8, 'Flamegrilled Beef on a skewer, served with peanut sauce.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Appetizers', 'Peanut Salad', 4, 'Casual salad with peanut dressing');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Curry', 'Yellow', 11, 'Coconut milk, yellow curry and other tasty things with chicken, served over rice');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Curry', 'Pineapple', 12, 'Coconut milk and other tasty things with chicken and pineapple, served over rice');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Curry', 'Panang', 11, 'Coconut milk and other special thai spices with chicken, served over rice');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Curry', 'Red', 10, 'Coconut milk, red curry and other tasty things with chicken, served over rice');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Noodles', 'Chicken Pad Thai', 9, 'The staple Thai dish; Noodles and chicken in a delicious peanutty sauce. Spicy.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Noodles', 'Beef Pad Thai', 11, 'The staple Thai dish; Noodles and beef in a delicious peanutty sauce. Spicy.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Noodles', 'Mix Pad Thai', 10, 'The staple Thai dish; Noodles, beef, and chicken in a delicious peanutty sauce. Spicy.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Desert', 'Green Tea Slushy', 6, 'That ice drink');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Thai', 'Desert', 'Banana Pudding', 5, 'Served with nilla wafers');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Appetizers', 'Mozarella Sticks', 4, 'Literally sticks of cheese deep fried. Served with Marinara');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Appetizers', 'Fried Mushrooms', 5, 'Mushrooms stuffed with a blend of cheese, spices, bacon, and jalapenos, then fried.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Appetizers', 'Bread and Oil', 2, 'What you expect at an italian restaurant');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Pasta', 'Penne Pesto', 7, 'Pleasant pesto penetrating penne pasta  ');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Pasta', 'Chicken Alfredo', 9, 'Some chicken, some alfredo');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Pasta', 'Spaghetti', 7, 'The classic dish: Just spaghetti. No sauce. Uncooked.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Stromboli', 'Meat Lovers', 8, 'Sausage, pepperoni, kobe filet, Flesh of the Prophet, black olives, thirteen snakes, a car battery, and mozarella. Served with marinara ');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Stromboli', 'Supreme', 8, 'Meat lovers, but with even more; ');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Stromboli', 'Vegetarian', 6, 'Every vegetable ever in a stromboli.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Desert', 'Cream Puffs', 4, 'Smol puffs stuffed with cream');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Italian', 'Desert', 'Gelato', 5, 'Like ice cream, but Italian');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Appetizers', 'Fried Pickles', 7, 'My friend Mikeys own recipe');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Appetizers', 'Onion Rings', 7, 'Rings of Saturn fried in horse oil. Served with cocktail sauce and shrimp');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Appetizers', 'Mozarella Sticks', 7, 'Sticks of Mozarella, could be fried, could not be');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Burger', 'GuacBurg', 12, 'A THICC Burger, with caramalized onions, guacamole, tomato, and pepper jack cheese');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Burger', 'BBQ Bacon Cheeseburger', 11, 'A less thicc but still thicc burger, four strips of human bacon and our signature Carolina Reaper BBQ Sauce');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Burger', 'SunnySide Up Burger', 9, 'Bangin out the block, its a burger with a fried egg. Wake yo punk self up');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Fries', 'Regular', 3, 'Potatos in their final form');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Fries', 'Garlic Fries', 4, 'French fries drowned in garlic');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Fries', 'Cajun Fries', 4, 'Fries seasoned with New Orleans mardi gras trash');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Fries', 'ChilliCheese Fries', 5, 'A chilli cheese dog, but with fries instead of the dog');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Desert', 'NY Cheesecake', 5, 'Cheesecake made by a real New Yorker');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Desert', 'Fried Cheesecake', 7, 'Cheesecake fried by a real New Yorker');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Burger', 'Desert', 'Oreo Milkshake', 3, 'Milkshake with oreos');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Chicken', 'Sandwich', 7, 'BBQ Chicken Sandwich');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Chicken', 'Plate', 9, 'BBQ Chicken plate, comes with two sides');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Pork', 'Pulled Pork', 9, 'Deliciously seasoned pulled pork, comes with sides');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Pork', 'Sausage Plate', 7, 'Plate of in-house turkey jalapeno sausage, with two sides');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Pork', 'Pork Ribs', 8, 'Ribs of the beast, smothered in chipoltle BBQ sauce. Comes with sides');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Beef', 'Sandwich', 7, 'BBQ Brisket on buns, comes with potato salad');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Beef', 'Plate', 9, 'BBQ Brisket, comes with two sides');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Beef', 'Special', 8, 'Its a mystery!');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Desert', 'BlackBerry Pie', 7, 'Tasty lil blackberry cobbler from down south.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Desert', 'Apple Pie', 7, 'Good ol apple pie from down south.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Barbecue', 'Desert', 'Key Lime Pie', 7, 'Tasty ol blackberry cobbler from down south.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Appetizers', 'Egg Rolls', 4, 'Who really knows whats in these?');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Appetizers', 'Crab Rangoons', 5, 'Crab meat, cream cheese and onions fried into a rangoon');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Noodles', 'Lo Mein', 7, 'Some noodles with some meat, probably chicken');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Noodles', 'Chow Mein', 8, 'Some other noodles with some meat, probably chicken');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Noodles', 'Mu Shu Pork', 8, 'Awesome dish of noodles and pork, lots of cashews.');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Fried Rice', 'Chicken', 7, 'Rice that is fried, with chicken');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Fried Rice', 'Beef', 9, 'Rice that is fried, with beef');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Fried Rice', 'Shrimp', 10, 'Rice that is fried, with shrimp');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Fried Rice', 'Mix', 9, 'Rice that is fried, with chicken, beef and shrimp');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Desert', 'Mooncake', 7, 'Cake fom the moooooon');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Desert', 'Prosperity Cake', 9, 'A cake that will literally make you prosper');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Chinese', 'Desert', 'Dragons Breath Cake', 5, 'Cake that smells like the breath of a dragon');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Appetizers', 'Gyoza', 4, 'Lil japanese dumplings');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Appetizers', 'Edamame', 5, 'Fried salted green beans looking things');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Noodles', 'Udon', 7, 'Some noodles');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Noodles', 'Yakisobe', 8, 'Some other noodles');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Noodles', 'Hiyamugi', 8, 'Noodles with things like flavors');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Sushi', 'Cali Roll', 6, 'Cucumber and imitation crab');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Sushi', 'Philidelphia Roll', 7, 'Smoked salmon and cream cheese');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Sushi', 'Spider Roll', 8, 'Sushi with live spiders');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Desert', 'Fried Icecream', 7, 'The ultimate delicious paradox');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Desert', 'Fried Bananas', 7, 'A fried banana');
INSERT INTO fakemenu (Cuisine, subCat, menuItem, price, description) VALUES('Japanese', 'Desert', 'Green Tea Icecream', 6, 'mochi flavored scream, great on the fried banana');
